(() => {
  'use strict';
  const dialog=document.querySelector('.lamp-dialog'),trigger=document.querySelector('.lamp-trigger'),core=window.KatmanyaLamp;
  if(!dialog||!trigger||!core||typeof dialog.showModal!=='function')return;
  const q=s=>dialog.querySelector(s),qa=s=>dialog.querySelectorAll(s),canvas=q('.lamp-preview'),ctx=canvas.getContext('2d'),sample=document.createElement('canvas'),sampleCtx=sample.getContext('2d',{willReadFrequently:true});if(!ctx||!sampleCtx)return;
  const file=q('.lamp-file'),original=q('.lamp-original'),status=q('.lamp-status'),contrast=q('.lamp-contrast'),brightness=q('.lamp-brightness'),text=q('.lamp-text'),quote=q('.lamp-quote'),download=q('.lamp-download'),light=q('.lamp-light');
  const reduce=matchMedia('(prefers-reduced-motion: reduce)'),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  let source=null,sourceUrl='',model=null,texture=null,revision=0,loading=false,exporting=false,building=false,start=0,progress=1,lit=false,warm=true,yaw=-.26,pitch=.08,frame=0,drag=null,saved=null,size={w:800,h:650,dpr:1};
  const caption=()=>text.value.trim().normalize('NFC').slice(0,24);
  function actions(){
    const ready=!!model&&!loading&&!building,busy=loading||exporting;
    q('.lamp-build').disabled=!ready||exporting;q('.lamp-settings').disabled=!source||busy;file.disabled=busy;q('.lamp-demo').disabled=busy;download.disabled=!ready||exporting;light.disabled=!ready||exporting;brightness.disabled=!ready||!lit||exporting;qa('[data-lamp-temperature]').forEach(b=>{b.disabled=!ready||exporting;b.setAttribute('aria-pressed',String((b.dataset.lampTemperature==='warm')===warm));});
    light.setAttribute('aria-pressed',String(lit));light.textContent=lit?'💡 IŞIĞI KAPAT':'💡 IŞIĞI AÇ';q('.lamp-empty').hidden=!!model;quote.setAttribute('aria-disabled',String(!ready));quote.setAttribute('tabindex',ready?'0':'-1');
    q('.lamp-contrast-value').textContent=contrast.value+'%';q('.lamp-brightness-value').textContent=brightness.value+'%';q('.lamp-model-tag').textContent='FOTOĞRAF LAMBASI / '+(lit?'IŞIK AÇIK':'IŞIK KAPALI');
    canvas.setAttribute('aria-label','Fotoğraf lambasının 3B önizlemesi. '+(lit?(warm?'Sıcak':'Beyaz')+' ışık açık, parlaklık yüzde '+brightness.value+'.':'Işık kapalı, beyaz kabartmalı panel.'));
    if(ready){const message=['Merhaba KATMANYA, fotoğrafımdan bir hatıra lambası için fiyat almak istiyorum.','Panel: beyaz, ışık geçiren fotoğraf kabartması','Işık tercihi: '+(warm?'Sıcak ışık':'Beyaz ışık'),'Fotoğraf kontrastı: %'+contrast.value,...(caption()?['Tabandaki not: '+caption()]:[]),'Orijinal fotoğrafımı ve PNG taslağını sohbete ekleyeceğim.','Ölçü, taban, LED ve adet detaylarını birlikte netleştirelim.'].join('\n');quote.href='https://wa.me/905304815341?text='+encodeURIComponent(message);}else quote.removeAttribute('href');
  }
  function makeTexture(){const c=document.createElement('canvas');c.width=600;c.height=70;const g=c.getContext('2d');g.fillStyle='#f3f1ec';g.font='600 40px Arial, sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(caption(),300,35,570);texture=c;}
  function rebuild(){if(!source)return;revision++;building=false;progress=1;const aspect=source.width/source.height,edge=128;sample.width=aspect>=1?edge:Math.max(12,Math.round(edge*aspect));sample.height=aspect>=1?Math.max(12,Math.round(edge/aspect)):edge;sampleCtx.clearRect(0,0,sample.width,sample.height);sampleCtx.drawImage(source,0,0,sample.width,sample.height);model=core.build({pixels:sampleCtx.getImageData(0,0,sample.width,sample.height).data,cols:sample.width,rows:sample.height,aspect,contrast:Number(contrast.value)});makeTexture();actions();requestPaint();}
  function view(tab){dialog.dataset.lampTab=tab;qa('[data-lamp-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lampTab===tab)));measure();}
  function measure(){const r=canvas.getBoundingClientRect();if(r.width>0&&r.height>0){size={w:r.width,h:r.height,dpr:Math.min(window.devicePixelRatio||1,2)};canvas.width=Math.round(size.w*size.dpr);canvas.height=Math.round(size.h*size.dpr);}requestPaint();}
  function paint(time){frame=0;if(!dialog.open||document.hidden)return;if(building){progress=reduce.matches?1:clamp((time-start)/2900,0,1);status.textContent=progress<1?'Katmanlar yükseliyor · %'+Math.round(progress*100):'Baskı hazır · hatırana ışık yaktık ✓';if(progress===1){building=false;lit=true;actions();}}
    ctx.setTransform(size.dpr,0,0,size.dpr,0,0);core.render(ctx,size.w,size.h,model,{yaw,pitch,lit,warm,brightness:Number(brightness.value),progress,caption:caption(),captionTexture:texture});if(building)requestPaint();}
  function requestPaint(){if(!frame&&dialog.open&&!document.hidden)frame=requestAnimationFrame(paint);}
  function print(){if(!model||loading||building||exporting)return;building=true;progress=0;lit=false;start=performance.now();status.textContent='Katmanlar yükseliyor…';view('preview');actions();requestPaint();}
  async function loadFile(selected){
    if(!selected)return;const current=++revision;loading=true;building=false;progress=1;status.textContent='Fotoğrafın ışık paneline dönüşüyor…';actions();requestPaint();let url='';
    try{if(!selected.size||selected.size>20*1024*1024)throw Error('size');if(selected.type&&!selected.type.startsWith('image/'))throw Error('type');url=URL.createObjectURL(selected);const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('decode'));i.src=url;});if(current!==revision||!dialog.open)return;
      if(!image.naturalWidth||!image.naturalHeight||image.naturalWidth*image.naturalHeight>40000000)throw Error('dimensions');const aspect=image.naturalWidth/image.naturalHeight;if(aspect<.35||aspect>2.8)throw Error('aspect');
      const c=document.createElement('canvas'),ratio=Math.min(1,1280/Math.max(image.naturalWidth,image.naturalHeight));c.width=Math.max(1,Math.round(image.naturalWidth*ratio));c.height=Math.max(1,Math.round(image.naturalHeight*ratio));c.getContext('2d').drawImage(image,0,0,c.width,c.height);
      if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=url;source=c;original.src=url;original.hidden=false;q('.lamp-original-empty').hidden=true;loading=false;contrast.value='100';lit=false;yaw=-.26;pitch=.08;q('.lamp-file-note').textContent='Fotoğraf hazır · Işığı açarak farkı gör';rebuild();status.textContent='Beyaz panel hazır · ışığı aç 💡';view('preview');
    }catch(e){if(current===revision&&dialog.open){const errors={size:'En fazla 20 MB’lık bir fotoğraf seç.',type:'Bir JPG, PNG veya WebP fotoğraf seç.',dimensions:'Fotoğraf çok büyük. Daha küçük bir kopyasını seç.',aspect:'Fotoğraf çok uzun veya dar. Normal bir fotoğraf kadrajıyla tekrar dene.'};q('.lamp-file-note').textContent=errors[e.message]||'Fotoğraf açılamadı. JPG, PNG veya WebP olarak tekrar dene.';status.textContent=model?'Önceki lamban duruyor':'Bir fotoğraf ekleyerek başla';}}
    finally{if(url!==sourceUrl&&url)URL.revokeObjectURL(url);if(current===revision){loading=false;actions();}file.value='';}
  }
  async function demo(){if(loading||exporting)return;const current=++revision;loading=true;actions();status.textContent='Örnek görsel açılıyor…';try{const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=new URL('assets/desk-set.webp',document.baseURI).href;});if(current!==revision||!dialog.open)return;const c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;c.getContext('2d').drawImage(image,0,0);const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('decode');if(current===revision&&dialog.open)await loadFile(blob);}catch{if(current===revision&&dialog.open){q('.lamp-file-note').textContent='Örnek açılamadı. Kendi fotoğrafını seçebilirsin.';loading=false;actions();}}}
  async function exportPNG(){if(!model||loading||building||exporting)return;const current=revision,snapshot=model,captionText=caption(),captionImage=texture,settings={warm,brightness:Number(brightness.value),contrast:contrast.value};exporting=true;actions();
    try{const c=document.createElement('canvas');c.width=1400;c.height=1400;const g=c.getContext('2d');g.fillStyle='#101711';g.fillRect(0,0,1400,1400);g.fillStyle='#c7fa5f';g.font='700 40px Arial, sans-serif';g.fillText('KATMANYA',60,78);g.fillStyle='#f3f1ec';g.font='600 30px Arial, sans-serif';g.fillText('Işıkta bir hatıra.',60,132);g.font='600 21px Arial, sans-serif';g.fillText('IŞIK KAPALI',100,206);g.fillStyle=settings.warm?'#ffe2b8':'#d9ecff';g.fillText('IŞIK AÇIK',800,206);
      for(const [i,on] of [false,true].entries()){g.save();g.translate(i*700,240);core.render(g,700,900,snapshot,{yaw:on?.12:-.16,pitch:.06,lit:on,warm:settings.warm,brightness:settings.brightness,caption:captionText,captionTexture:captionImage,clear:false});g.restore();}
      g.fillStyle='#f3f1ec';g.font='600 23px Arial, sans-serif';g.fillText((settings.warm?'Sıcak ışık':'Beyaz ışık')+' · Kontrast %'+settings.contrast+(captionText?' · '+captionText:''),60,1190);g.fillStyle='#a9b69e';g.font='18px Arial, sans-serif';g.fillText('Işık simülasyonu · Malzeme, LED ve ölçü detayları teklif sırasında netleşir.',60,1240);g.fillStyle='#c7fa5f';g.font='700 23px Arial, sans-serif';g.fillText('katmanya.com  /  @katmanya_3d',60,1340);
      const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('png');if(current!==revision||!dialog.open)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='katmanya-fotograf-lambasi.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='Lambanın taslağı indirildi ✓';
    }catch{if(current===revision)status.textContent='İndirme tamamlanamadı. Tekrar deneyebilirsin.';}finally{exporting=false;actions();}}
  function open(){if(dialog.open)return;saved={y:window.scrollY,style:{position:document.body.style.position,top:document.body.style.top,width:document.body.style.width}};document.body.style.position='fixed';document.body.style.top=-saved.y+'px';document.body.style.width='100%';dialog.showModal();view(model?'preview':'edit');actions();q('.lamp-close').focus({preventScroll:true});}
  function close(){revision++;loading=false;building=false;progress=1;drag=null;if(frame)cancelAnimationFrame(frame);frame=0;if(saved){Object.assign(document.body.style,saved.style);window.scrollTo({top:saved.y,left:0,behavior:'instant'});saved=null;}actions();trigger.focus({preventScroll:true});}
  trigger.disabled=false;trigger.addEventListener('click',open);q('.lamp-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',close);file.addEventListener('change',()=>loadFile(file.files?.[0]));q('.lamp-demo').addEventListener('click',demo);q('.lamp-build').addEventListener('click',print);download.addEventListener('click',exportPNG);
  contrast.addEventListener('input',()=>{rebuild();status.textContent='Fotoğraf kontrastı güncellendi';});text.addEventListener('input',()=>{revision++;makeTexture();actions();requestPaint();});light.addEventListener('click',()=>{lit=!lit;actions();status.textContent=lit?'Işık açık · hatıran görünür 💡':'Işık kapalı · beyaz kabartma';requestPaint();});brightness.addEventListener('input',()=>{actions();requestPaint();});qa('[data-lamp-temperature]').forEach(b=>b.addEventListener('click',()=>{warm=b.dataset.lampTemperature==='warm';actions();requestPaint();}));qa('[data-lamp-tab]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.lampTab)));qa('[data-lamp-view]').forEach(b=>b.addEventListener('click',()=>{yaw={left:-.55,front:0,right:.55}[b.dataset.lampView];pitch=.08;requestPaint();}));
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0||building||drag)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();});canvas.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;yaw=clamp(yaw+(e.clientX-drag.x)*.006,-1.15,1.15);pitch=clamp(pitch+(e.clientY-drag.y)*.004,-.1,.35);drag.x=e.clientX;drag.y=e.clientY;requestPaint();});['pointerup','pointercancel','lostpointercapture'].forEach(type=>canvas.addEventListener(type,e=>{if(drag?.id!==e.pointerId)return;drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}));
  canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();if(e.key==='Home'){yaw=-.26;pitch=.08;}else if(e.key==='ArrowLeft'||e.key==='ArrowRight')yaw=clamp(yaw+(e.key==='ArrowRight'?.1:-.1),-1.15,1.15);else pitch=clamp(pitch+(e.key==='ArrowUp'?-.05:.05),-.1,.35);requestPaint();});
  window.addEventListener('resize',()=>{if(dialog.open)measure();});window.visualViewport?.addEventListener('resize',()=>{if(dialog.open)measure();});if(typeof ResizeObserver==='function')new ResizeObserver(()=>{if(dialog.open)measure();}).observe(q('.lamp-model'));document.addEventListener('visibilitychange',()=>{if(document.hidden){if(frame)cancelAnimationFrame(frame);frame=0;}else requestPaint();});
})();
