(() => {
  'use strict';
  const dialog=document.querySelector('.voice-dialog'),trigger=document.querySelector('.voice-trigger'),core=window.KatmanyaVoice;
  if(!dialog||!trigger||!core||typeof dialog.showModal!=='function')return;
  const q=s=>dialog.querySelector(s),qa=s=>dialog.querySelectorAll(s),canvas=q('.voice-preview'),ctx=canvas.getContext('2d'),waveCanvas=q('.voice-wave'),waveCtx=waveCanvas.getContext('2d');if(!ctx||!waveCtx)return;
  const file=q('.voice-file'),record=q('.voice-record'),audio=q('.voice-audio'),note=q('.voice-source-note'),status=q('.voice-status'),textInput=q('.voice-text'),quote=q('.voice-quote'),download=q('.voice-download');
  const reduce=matchMedia('(prefers-reduced-motion: reduce)'),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  let wave=null,duration=0,model=null,color='Yeşil',sourceKind='',sourceUrl='',revision=0,loading=false,exporting=false,building=false,start=0,progress=1,frame=0,yaw=-.14,pitch=1.03,drag=null,saved=null,size={w:800,h:650,dpr:1};
  let session=null,pendingMic=false,clock=0,autoStop=0;
  const canRecord=()=>!!(navigator.mediaDevices?.getUserMedia&&window.MediaRecorder);
  const label=()=>textInput.value.trim().normalize('NFC').slice(0,18);
  function actions(){
    const busy=loading||pendingMic||!!session,ready=!!model&&!building&&!busy;
    q('.voice-build').disabled=!model||building||busy;q('.voice-replay').disabled=!ready;download.disabled=!ready||exporting;q('.voice-settings').disabled=busy||!wave;
    file.disabled=busy;record.disabled=loading||pendingMic||!canRecord();q('.voice-demo').disabled=busy;
    record.textContent=session?'■ KAYDI BİTİR':pendingMic?'İZİN BEKLENİYOR…':'● SES KAYDET';record.dataset.recording=String(!!session);
    qa('[data-voice-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.voiceColor===color)));
    q('.voice-empty').hidden=!!model;audio.hidden=!sourceUrl;quote.setAttribute('aria-disabled',String(!ready));quote.setAttribute('tabindex',ready?'0':'-1');
    if(ready){const message=['Merhaba KATMANYA, ses dalgamdan kabartmalı bir anahtarlık için fiyat almak istiyorum.','Renk: '+color,'Ses süresi: '+duration.toFixed(1)+' sn',...(label()?['Kısa not: '+label()]:[]),'Dalga kodu (v1): '+core.code(wave),'PNG taslağını sohbete ekleyeceğim.','Ölçü ve adedi birlikte netleştirelim.'].join('\n');quote.href='https://wa.me/905304815341?text='+encodeURIComponent(message);}else quote.removeAttribute('href');
  }
  function textMask(){const c=document.createElement('canvas');c.width=core.COLS;c.height=core.ROWS;const g=c.getContext('2d',{willReadFrequently:true});g.fillStyle='#fff';g.font='700 7px Arial, sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(label(),core.COLS*.55,core.ROWS*.8,108);const pixels=g.getImageData(0,0,c.width,c.height).data;return Uint8Array.from({length:c.width*c.height},(_,i)=>pixels[i*4+3]>90?1:0);}
  function rebuild(){revision++;building=false;progress=1;model=wave?core.build({wave,color,text:textMask()}):null;actions();requestPaint();}
  function drawWave(){waveCtx.clearRect(0,0,600,110);waveCtx.strokeStyle='#5d704d';waveCtx.lineWidth=1;waveCtx.beginPath();waveCtx.moveTo(16,55);waveCtx.lineTo(584,55);waveCtx.stroke();if(!wave)return;waveCtx.fillStyle='#c7fa5f';for(let i=0;i<wave.length;i++){const high=3+wave[i]*80;waveCtx.fillRect(18+i*566/wave.length,55-high/2,5,high);}waveCanvas.setAttribute('aria-label','Sesinin '+duration.toFixed(1)+' saniyelik dalga biçimi');}
  function view(tab){dialog.dataset.voiceTab=tab;qa('[data-voice-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.voiceTab===tab)));measure();}
  function measure(){const r=canvas.getBoundingClientRect();if(r.width>0&&r.height>0){size={w:r.width,h:r.height,dpr:Math.min(window.devicePixelRatio||1,2)};canvas.width=Math.round(size.w*size.dpr);canvas.height=Math.round(size.h*size.dpr);}requestPaint();}
  function paint(time){frame=0;if(!dialog.open||document.hidden)return;if(building){progress=reduce.matches?1:clamp((time-start)/2600,0,1);status.textContent=progress<1?'Katmanlar yükseliyor · %'+Math.round(progress*100):'Sesin şekle dönüştü ✓';if(progress===1){building=false;actions();}}
    ctx.setTransform(size.dpr,0,0,size.dpr,0,0);core.render(ctx,size.w,size.h,model,{yaw,pitch,progress});if(building)requestPaint();}
  function requestPaint(){if(!frame&&dialog.open&&!document.hidden)frame=requestAnimationFrame(paint);}
  function print(){if(!model||loading||session||pendingMic||building)return;audio.pause();building=true;progress=0;start=performance.now();status.textContent='Katmanlar yükseliyor…';actions();view('preview');requestPaint();}
  function wav(channels,rate,length){
    const buffer=new ArrayBuffer(44+length*channels.length*2),v=new DataView(buffer),write=(at,s)=>{for(let i=0;i<s.length;i++)v.setUint8(at+i,s.charCodeAt(i));};
    write(0,'RIFF');v.setUint32(4,buffer.byteLength-8,true);write(8,'WAVE');write(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels.length,true);v.setUint32(24,rate,true);v.setUint32(28,rate*channels.length*2,true);v.setUint16(32,channels.length*2,true);v.setUint16(34,16,true);write(36,'data');v.setUint32(40,buffer.byteLength-44,true);
    let offset=44;for(let i=0;i<length;i++)for(const channel of channels){const n=clamp(channel[i]||0,-1,1);v.setInt16(offset,n*(n<0?32768:32767),true);offset+=2;}return new Blob([buffer],{type:'audio/wav'});
  }
  function commitAudio(channels,rate,kind,current){
    const result=core.envelope(channels,rate);if(current!==revision||!dialog.open)return;
    const blob=wav(channels,rate,Math.floor(result.duration*rate));audio.pause();if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(blob);audio.src=sourceUrl;audio.load();wave=result.wave;duration=result.duration;sourceKind=kind;file.value='';yaw=-.14;pitch=1.03;loading=false;
    note.textContent=kind+' · '+duration.toFixed(1)+' sn hazır';status.textContent='Sesinin dalgası hazır · baskıyı izle';drawWave();rebuild();view('edit');
  }
  async function loadAudio(blob,kind){
    if(!blob)return;const current=++revision;loading=true;building=false;progress=1;status.textContent='Sesinin dalgası çıkarılıyor…';actions();requestPaint();let ac;
    try{if(!blob.size||blob.size>20*1024*1024)throw Error('size');const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('unsupported');ac=new AC();const data=await blob.arrayBuffer();if(current!==revision)return;const decoded=await ac.decodeAudioData(data);if(current!==revision||!dialog.open)return;if(decoded.duration>120)throw Error('long');const channels=Array.from({length:Math.min(2,decoded.numberOfChannels)},(_,i)=>decoded.getChannelData(i));commitAudio(channels,decoded.sampleRate,kind,current);
    }catch(e){if(current===revision&&dialog.open){const errors={silent:'Ses çok düşük veya kayıt sessiz. Daha yakından konuşup tekrar dene.',short:'Kayıt çok kısa. Biraz daha uzun bir ses ekle.',size:'En fazla 20 MB’lık bir ses dosyası seç.',long:'Dosya çok uzun. En fazla 2 dakikalık bir ses seç; ilk 8 saniyesi kullanılır.',unsupported:'Bu tarayıcı sesi işleyemiyor. Güncel Safari veya Chrome ile dene.'};note.textContent=errors[e.message]||'Ses açılamadı. MP3, M4A veya WAV dosyasıyla tekrar dene.';status.textContent=wave?'Önceki tasarımın duruyor':'Bir ses ekleyerek başla';}}
    finally{if(ac)try{await ac.close();}catch{}if(current===revision){loading=false;file.value='';actions();}}
  }
  function stopTracks(stream){stream?.getTracks().forEach(t=>t.stop());}
  function clearClock(){clearInterval(clock);clearTimeout(autoStop);clock=0;autoStop=0;}
  function stopRecording(discard=false){const s=session;if(!s)return;s.discard=discard;clearClock();if(s.recorder.state!=='inactive')s.recorder.stop();stopTracks(s.stream);}
  async function startRecording(){
    if(session){stopRecording();return;}if(pendingMic||loading||!canRecord())return;const current=++revision;pendingMic=true;building=false;progress=1;audio.pause();status.textContent='Mikrofon iznini bekliyoruz';actions();let stream;
    try{stream=await navigator.mediaDevices.getUserMedia({audio:true});if(current!==revision||!dialog.open){stopTracks(stream);return;}
      const MR=window.MediaRecorder,mime=['audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(t=>MR.isTypeSupported(t)),recorder=new MR(stream,mime?{mimeType:mime}:undefined),s={stream,recorder,chunks:[],discard:false,current,started:performance.now()};session=s;pendingMic=false;
      recorder.ondataavailable=e=>{if(e.data.size)s.chunks.push(e.data);};recorder.onerror=()=>{s.discard=true;stopRecording(true);note.textContent='Kayıt tamamlanamadı. Ses dosyası seçerek devam edebilirsin.';status.textContent='Kayıt hatası';};
      recorder.onstop=()=>{stopTracks(s.stream);if(session===s){clearClock();session=null;}if(s.discard||current!==revision||!dialog.open){actions();return;}if(!s.chunks.length){note.textContent='Kayıt boş kaldı. Tekrar dene.';actions();return;}loadAudio(new Blob(s.chunks,{type:recorder.mimeType||mime||'audio/webm'}),'Ses kaydın');};
      recorder.start();note.textContent='Konuşabilirsin · 0 / 8 sn';status.textContent='Sesin kaydediliyor ●';clock=setInterval(()=>{if(session===s)note.textContent='Konuşabilirsin · '+Math.min(8,Math.floor((performance.now()-s.started)/1000))+' / 8 sn';},250);autoStop=setTimeout(()=>stopRecording(),8000);actions();
    }catch(e){stopTracks(stream);if(current===revision&&dialog.open){pendingMic=false;note.textContent=e.name==='NotAllowedError'?'Mikrofon izni verilmedi. Ses dosyası seçebilir veya örneği deneyebilirsin.':'Mikrofon açılamadı. Ses dosyası seçerek devam edebilirsin.';status.textContent=wave?'Önceki tasarımın duruyor':'Bir ses ekleyerek başla';actions();}}
  }
  function demo(){if(loading||session||pendingMic)return;const rate=16000,pcm=new Float32Array(rate*3);for(let i=0;i<pcm.length;i++){const t=i/rate,e=Math.pow(Math.sin(Math.PI*t/3),2)*(.16+.84*Math.pow(Math.sin(t*5.7),2));pcm[i]=e*(Math.sin(2*Math.PI*220*t)*.4+Math.sin(2*Math.PI*330*t)*.18);}loadAudio(wav([pcm],rate,pcm.length),'Örnek ses dalgası');}
  async function exportPNG(){if(!model||building||loading||session||pendingMic||exporting)return;const current=revision,snapshot=model,caption=label(),seconds=duration,kind=sourceKind;exporting=true;actions();
    try{const c=document.createElement('canvas');c.width=1400;c.height=1400;const g=c.getContext('2d');g.fillStyle='#111a14';g.fillRect(0,0,1400,1400);g.fillStyle='#c7fa5f';g.font='700 40px Arial, sans-serif';g.fillText('KATMANYA',60,78);g.fillStyle='#f3f1ec';g.font='600 30px Arial, sans-serif';g.fillText('Sesin katmanlarda.',60,132);g.save();g.translate(0,170);core.render(g,1400,850,snapshot,{clear:false});g.restore();g.fillStyle='#c7fa5f';for(let i=0;i<snapshot.wave.length;i++){const h=4+snapshot.wave[i]*100;g.fillRect(120+i*1160/snapshot.wave.length,1050-h/2,10,h);}g.fillStyle='#f3f1ec';g.font='600 24px Arial, sans-serif';g.fillText(snapshot.color+' · '+seconds.toFixed(1)+' sn'+(caption?' · '+caption:''),60,1190);g.fillStyle='#a9b69e';g.font='18px Arial, sans-serif';g.fillText(kind+' · Ses dalgası anahtarlığı tasarım önizlemesi',60,1240);g.fillStyle='#c7fa5f';g.font='700 23px Arial, sans-serif';g.fillText('katmanya.com  /  @katmanya_3d',60,1340);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('png');if(current!==revision||!dialog.open)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='katmanya-ses-dalgasi.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='Ses dalganın taslağı indirildi ✓';
    }catch{if(current===revision)status.textContent='İndirme tamamlanamadı. Tekrar deneyebilirsin.';}finally{exporting=false;actions();}}
  function open(){if(dialog.open)return;saved={y:window.scrollY,style:{position:document.body.style.position,top:document.body.style.top,width:document.body.style.width}};document.body.style.position='fixed';document.body.style.top=-saved.y+'px';document.body.style.width='100%';dialog.showModal();if(!canRecord())note.textContent='Bu tarayıcıda kayıt yok. Ses dosyası seçebilir veya örneği deneyebilirsin.';view(model?'preview':'edit');actions();drawWave();q('.voice-close').focus({preventScroll:true});}
  function close(){revision++;pendingMic=false;loading=false;stopRecording(true);session=null;clearClock();building=false;progress=1;drag=null;audio.pause();if(frame)cancelAnimationFrame(frame);frame=0;if(saved){Object.assign(document.body.style,saved.style);window.scrollTo({top:saved.y,left:0,behavior:'instant'});saved=null;}actions();trigger.focus({preventScroll:true});}
  trigger.disabled=false;trigger.addEventListener('click',open);q('.voice-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',close);record.addEventListener('click',startRecording);
  file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;if(selected.type&&!selected.type.startsWith('audio/')&&!/\.(mp3|m4a|wav|ogg|webm|aac|flac)$/i.test(selected.name)){note.textContent='Bir ses dosyası seç. MP3, M4A veya WAV kullanabilirsin.';file.value='';return;}loadAudio(selected,'Ses dosyan');});
  q('.voice-demo').addEventListener('click',demo);q('.voice-build').addEventListener('click',print);q('.voice-replay').addEventListener('click',print);download.addEventListener('click',exportPNG);textInput.addEventListener('input',()=>{rebuild();status.textContent='Notun güncellendi · baskıyı izle';});qa('[data-voice-color]').forEach(b=>b.addEventListener('click',()=>{color=b.dataset.voiceColor;rebuild();status.textContent='Rengin güncellendi · baskıyı izle';}));qa('[data-voice-tab]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.voiceTab)));
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0||building||drag)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();});canvas.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;yaw=clamp(yaw+(e.clientX-drag.x)*.006,-1.3,1.3);pitch=clamp(pitch+(e.clientY-drag.y)*.005,.45,1.5);drag.x=e.clientX;drag.y=e.clientY;requestPaint();});['pointerup','pointercancel','lostpointercapture'].forEach(type=>canvas.addEventListener(type,e=>{if(drag?.id!==e.pointerId)return;drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}));
  window.addEventListener('resize',()=>{if(dialog.open)measure();});window.visualViewport?.addEventListener('resize',()=>{if(dialog.open)measure();});if(typeof ResizeObserver==='function')new ResizeObserver(()=>{if(dialog.open)measure();}).observe(q('.voice-model'));
  document.addEventListener('visibilitychange',()=>{if(document.hidden){if(frame)cancelAnimationFrame(frame);frame=0;audio.pause();if(session)stopRecording();}else requestPaint();});window.addEventListener('pagehide',()=>{revision++;pendingMic=false;loading=false;stopRecording(true);clearClock();audio.pause();actions();});
})();
